# Generated by Django 3.2.9 on 2023-02-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_no',
            name='password',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
