# Generated by Django 3.2.9 on 2023-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='projects')),
                ('Link', models.URLField()),
            ],
        ),
    ]
