# Generated by Django 3.2.9 on 2023-03-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Color',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
