# Generated by Django 3.2.9 on 2023-03-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_project_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=150)),
                ('Date_Time', models.DateTimeField()),
            ],
        ),
    ]
